# -*- coding: utf-8 -*-
"""KMeans-simplified.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqxbpfvEfmydqYAEXrbRg4oFMuT3ik8U
"""

import random
import math

def distance(point1, point2):
    total = 0
    for i in range(len(point1)):
        total += (point1[i] - point2[i]) ** 2
    return math.sqrt(total)

def mean(points):
    n = len(points)
    dims = len(points[0])
    result = []
    for i in range(dims):
        s = 0
        for j in range(n):
            s += points[j][i]
        result.append(s / n)
    return result

def kmeans(data, k, max_iters=100):
    centroids = random.sample(data, k)
    for _ in range(max_iters):
        clusters = [[] for _ in range(k)]
        for point in data:
            distances = []
            for c in centroids:
                d = distance(point, c)
                distances.append(d)
            min_index = distances.index(min(distances))
            clusters[min_index].append(point)

        new_centroids = []
        for cluster in clusters:
            if cluster:
                new_c = mean(cluster)
            else:
                new_c = random.choice(data)
            new_centroids.append(new_c)

        if new_centroids == centroids:
            break
        centroids = new_centroids

    return centroids, clusters

data = [
    [1, 2], [1.5, 1.8], [5, 8],
    [8, 8], [1, 0.6], [9, 11],
    [8, 2], [10, 2], [9, 3]
]

final_centroids, final_clusters = kmeans(data, k=3)

print("Centroids:")
for c in final_centroids:
    print(c)

print("\nClusters:")
for i, cluster in enumerate(final_clusters):
    print("Cluster", i+1, ":", cluster)